version: "3.9"

services:

  angular_app:
    container_name: angular_app
    image: tcproj-angular_app:1.0.0
    build: ./webapp/tciprojapp/
    ports:
      - 8080:80
    depends_on:
      - spring_app
  
  spring_app:
    container_name: spring_app
    image: tcproj-spring_app:1.0.0
    build: .
    ports:
      - 9090:9090
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
